### PR TITLE
Riecoin Support

### PR DESCRIPTION
**Pull request by ahmedbodi**

### CODE REVIEW

**Comment by rabbie** [comment]
I'm getting "Incorrect size of ntime. Expected 16 chars" with this update on riecoin.. is there a specific ntime setting somewhere that needs to be adjusted ?

**Comment by ahmedbodi** [comment]
unsure. ive just pulled gatra's changes

**Comment by rabbie** [comment]
Thank you akhi.

**Comment by ahmedbodi** [comment]
no problem brother

**Pull request merged**
